version: "3.8"

services:

  user-be:
    image: openjdk:21
    container_name: user-be
    ports:
      - 8080:8080
      - 8000:8000

    expose:
      - "8000"

    depends_on:
      - user-db
    networks:
      - my-net
      #- shared-net
    volumes:
      #- ./build/libs/User-0.0.1-SNAPSHOT.jar:/app/app.jar
      - ./User-0.0.1-SNAPSHOT.jar:/app/app.jar

    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar
  user-db:
    image: mongo:5.0
    container_name: user-db
    ports:
      - 27017:27017
    networks:
      - my-net
      #- shared-net
networks:
  my-net:
    driver: "bridge"
    name: my-net
  #shared-net:
    #external: true

